[pytest]

addopts =
    -v
    --pw-base-url=https://tutorialsninja.com/demo/
    --pw-video=retain-on-failure
    --pw-screenshot=only-on-failure
    --pw-tracing=retain-on-failure
    --html=reports/myreport.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results
    --numprocesses=auto
    --reruns=2
    --reruns-delay=2


markers=
    sanity
    regression
    datadriven
    end_to_end

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
